### Get all brands (only 10 items)
GET http://localhost:5000/api/brands

### Get brands above half of count
GET http://localhost:5000/api/brands/half

### Get brands by (array) names
POST http://localhost:5000/api/brands/by-names
content-type: application/json

{
  "brandNames": ["Honda", "Bosch", "Lenovo"]
}

### Delete brands by (array) names
DELETE http://localhost:5000/api/brands/del-brands
Content-Type: application/json

{
  "brandNames": ["Samsung", "Sony", "LG"]
}

### Get brand by id
GET http://localhost:5000/api/brands/1

### Create new brand
POST http://localhost:5000/api/brands HTTP/1.1
content-type: application/json

{
  "title": "New brand",
  "description": "New test brand"
}

### Update exists brand by id
PUT http://localhost:5000/api/brands HTTP/1.1
content-type: application/json

{
  "id": "1",
  "title": "Updated brand",
  "description": "Updated description brand"
}

### Update book PATCH
PATCH http://localhost:5000/api/brands/1 HTTP/1.1
content-type: application/json

{
  "title": "Patched brand",
  "description": "UpdDesc",
  "logo": "null"
}

### Delete brand by id
DELETE  http://localhost:5000/api/brands/7 HTTP/1.1
