// Get all brands
GET http://localhost:5000/api/brands

###

// Get brand by id
GET http://localhost:5000/api/brands/9

###

// Create brand (Success)
POST http://localhost:5000/api/brands HTTP/1.1
content-type: application/json

{
  "title": "New brand",
  "description": "New test brand"
}

###

// Update brand
PUT http://localhost:5000/api/brands HTTP/1.1
content-type: application/json

{
  "id": "1",
  "title": "Update brand",
  "description": "Updated test brand"
}

###

// Delete brand
DELETE  http://localhost:5000/api/brands/11 HTTP/1.1
