### Get all Items (only 10 items)
GET http://localhost:5000/api/Items

### Get Items above half of count
GET http://localhost:5000/api/Items/half

### Get Items by (array) names
POST http://localhost:5000/api/Items/by-names
content-type: application/json

{
  "ItemId": ["10", "12", "15"]
}

### Delete Items by (array) names
DELETE http://localhost:5000/api/Items/del-Items
Content-Type: application/json

{
  "ItemId": ["4", "5", "6"]
}

### Get Item by id
GET http://localhost:5000/api/Items/9

### Create new Item
POST http://localhost:5000/api/Items HTTP/1.1
content-type: application/json

{
  "price": "2499.99",
  "amount": 100500,
  "categoryTitle": "Beauty",
  "typeTitle": "Refrigerators",
  "brandTitle": "Burberry",
  "modelTitle": "HP Spectre x360",
  "storeTitle": "AutoMart"
}

### Update exists Item by id
PUT http://localhost:5000/api/Items HTTP/1.1
content-type: application/json

{
  "id": "1",
  "price": "5099.99",
  "amount": 999,
  "categoryTitle": "Beauty",
  "typeTitle": "Refrigerators",
  "brandTitle": "Burberry",
  "modelTitle": "HP Spectre x360",
  "storeTitle": "AutoMart"
}

### Delete Item by id
DELETE  http://localhost:5000/api/Items/7 HTTP/1.1
