### Get the number of models of each brand
GET http://localhost:5000/api/items-orders/count-brand

### Get the number of goods of each type in each stores
GET http://localhost:5000/api/items-orders/items-on-stores

### Get top customer
GET http://localhost:5000/api/items-orders/top-customer

### Get the most expensive purchase
GET http://localhost:5000/api/items-orders/exp-purchase

